### ISSUE TITLE
Issue when upgrading from Rails 4.2.5.2 to 4.2.6

### ISSUE THREAD

**Issue by nesrual** [SchemaPlus/schema_plus#230]
When trying to migrate I get the following error. Migrations works fine in 4.2.5.2 however when upgrading to 4.2.6 it seems to be broken:

    rake aborted!
    NoMethodError: undefined method `values' for []:Array
    Did you mean?  values_at
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/schema_plus_foreign_keys-0.1.2/lib/schema_plus/foreign_keys/middleware/sql.rb:8:in `after'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/modware-0.1.2/lib/modware/stack.rb:47:in `block in execute'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/modware-0.1.2/lib/modware/stack.rb:46:in `each'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/modware-0.1.2/lib/modware/stack.rb:46:in `execute'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/modware-0.1.2/lib/modware/stack.rb:20:in `start'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/schema_monkey-2.1.3/lib/schema_monkey/stack.rb:34:in `start'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/schema_plus_core-0.6.2/lib/schema_plus/core/active_record/connection_adapters/abstract_adapter.rb:47:in `visit_TableDefinition'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:222:in `create_table'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/schema_plus_core-0.6.2/lib/schema_plus/core/active_record/connection_adapters/abstract_adapter.rb:28:in `block in create_table'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/modware-0.1.2/lib/modware/stack.rb:55:in `call_implementation'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/modware-0.1.2/lib/modware/stack.rb:85:in `_modware_continue'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/modware-0.1.2/lib/modware/stack.rb:74:in `block in _modware_call'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/schema_plus_foreign_keys-0.1.2/lib/schema_plus/foreign_keys/middleware/migration.rb:14:in `around'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/modware-0.1.2/lib/modware/stack.rb:73:in `_modware_call'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/modware-0.1.2/lib/modware/stack.rb:83:in `_modware_continue'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/modware-0.1.2/lib/modware/stack.rb:77:in `_modware_call'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/modware-0.1.2/lib/modware/stack.rb:44:in `execute'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/modware-0.1.2/lib/modware/stack.rb:20:in `start'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/schema_monkey-2.1.3/lib/schema_monkey/stack.rb:34:in `start'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/schema_plus_core-0.6.2/lib/schema_plus/core/active_record/connection_adapters/abstract_adapter.rb:27:in `create_table'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/activerecord-4.2.6/lib/active_record/schema_migration.rb:29:in `create_table'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:836:in `initialize_schema_migrations_table'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/activerecord-4.2.6/lib/active_record/migration.rb:925:in `initialize'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/activerecord-4.2.6/lib/active_record/migration.rb:823:in `new'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/activerecord-4.2.6/lib/active_record/migration.rb:823:in `up'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/activerecord-4.2.6/lib/active_record/migration.rb:801:in `migrate'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/activerecord-4.2.6/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/bin/ruby_executable_hooks:15:in `eval'
    /Users/XXXXX/.rvm/gems/ruby-2.3.0@some_gemset/bin/ruby_executable_hooks:15:in `<main>'
    Tasks: TOP => db:migrate
    (See full trace by running task with --trace)

Using Ruby 2.3 under OSX, RVM 1.26.11

**Comment by ronen** [comment]
Hi, see SchemaPlus/schema_plus_foreign_keys#6 that will hopefully take care of this.  Thanks to @btsuhako!

(I haven't yet had had a chance to release it, so you'd need to run schema_plus_foreign_keys from master)

**Comment by btsuhako** [comment]
You're welcome @ronen! Sorry, I think I pushed two commits in my pull request, but only the first one (commit `110d09bbcff52f7e8a1339e517e33d180d8114b4`) should be merged to fix this issue.

**Comment by webhive** [comment]
Confirm ths bug

Using ruby 2.2.1 (rvm), Linux

**Comment by lowjoel** [comment]
@ronen need me to release a new version?

**Comment by ronen** [comment]
Hi all, with further work by @dholdren in SchemaPlus/schema_plus_foreign_keys#8 and some more tweaks to schema_dev, the builds all seem to be passing cleanly for all tested versions of AR.

I've just released v0.1.3 of schema_plus_foreign_keys  (beat you to it @lowjoel, thanks for the offer :)

Thanks everyone.  I'm closing this out, but don't hestitate to open another if something still seems awry.
